# Generated by Django 3.0.8 on 2020-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Clothing', 'Clothing'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
