# Generated by Django 3.0.8 on 2020-08-27 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200826_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
