# Generated by Django 3.0.8 on 2020-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200827_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
