# Generated by Django 3.0.8 on 2020-08-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlist',
            new_name='watchers',
        ),
    ]
