# Generated by Django 3.0.8 on 2020-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
