# Generated by Django 3.0.8 on 2020-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201005_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Clothing', 'Clothing'), ('Other', 'Other')], default='Other', max_length=15),
        ),
    ]
